name: CI
on:
  - push

jobs:
  ci:
    name: Lint, Type Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Wait for preview deployments
        uses: dicolabs/await-vercel-monorepo-preview@v1.9
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-team-id: 'team_YyUN9ndjTfXu4BbxXKoZmJHP'
          vercel-deployment-names: 'scratch-tutoring-web-app, scratch-tutoring-admin, scratch-tutoring-gui'
          max-timeout: 600
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn bootstrap
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn type-check
